### ISSUE TITLE
Source lines too long to compile using PGI compiler

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/coupler#1]
PGF90-S-0285-Source line too long (src/coupler/surface_flux.F90: 39)
PGF90-S-0285-Source line too long (src/coupler/flux_exchange.F90: 198)
PGF90-S-0285-Source line too long (src/coupler/coupler_main.F90: 105)
PGF90-S-0285-Source line too long (src/coupler/coupler_main.F90: 106)
PGF90-S-0285-Source line too long (src/coupler/coupler_main.F90: 114)
PGF90-S-0285-Source line too long (coupler/coupler_main.F90: 115)
PGF90-S-0285-Source line too long (src/coupler/coupler_main.F90: 117)
PGF90-S-0285-Source line too long (src/coupler/coupler_main.F90: 120)

These _comment_ lines are far in excess of the 132 characters allowed in Fortran 95.

**Comment by underwoo** [comment]
A fix is in the internal git, and will be pushed out when the next release is ready.

**Comment by adcroft** [comment]
Any progress on this? We'd like to upgrade to ulm_201505 but this is holding us up. Thx.

**Comment by underwoo** [comment]
Branch dev/master has the fix for this.  We are currently testing this as part of the next production release.  Once ready, this will be merged into the master branch.
