### ISSUE TITLE
Nonnegative width required in format string (gnu compiler)

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/coupler#2]
src/coupler/coupler_main.F90:1275.14:

20  format (i,5i4,2x,a3)
              1
Error: Nonnegative width required in format string at (1)

**Comment by underwoo** [comment]
We have a fix for this, and it will be updated soon.

In the interim, you can change the line to be:

20 format (i6,5i4,2x,a3)

**Comment by underwoo** [comment]
Branch dev/master has a fix for this issue.  After our internal testing is completed, this will be merged into master.
